version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: microlend-jenkins
    restart: always

    user: root

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - jenkins_data:/var/jenkins_home

      # Docker socket
      - /var/run/docker.sock:/var/run/docker.sock

      # Project folder
      - C:\Users\SANDRINE\MicroLend\MicroLend:/workspace

    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true

volumes:
  jenkins_data: