version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: microlend-jenkins
    restart: always
    user: root   # root so Jenkins can run Docker commands
    ports:
      - "8080:8080"    # Jenkins web UI
      - "50000:50000"  # Jenkins agent port
    volumes:
      # Persist Jenkins data (jobs, plugins, config) between restarts
      - jenkins_data:/var/jenkins_home
      # Mount the host Docker socket so Jenkins can build Docker images
      # This is called "Docker-in-Docker" (DinD)
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount your project folder so Jenkins can access your code
      - C:\Users\SANDRINE\MicroLend\MicroLend:/workspace
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true

volumes:
  jenkins_data: