version: '3.8'

services:
  postgres-repayments:
    image: postgres:15-alpine
    container_name: microlend-repayments-postgres
    restart: always
    environment:
      POSTGRES_USER: microlend_user
      POSTGRES_PASSWORD: microlend_pass
      POSTGRES_DB: microlend_repayments_db
    ports:
      - "5434:5432"
    volumes:
      - repayments_postgres_data:/var/lib/postgresql/data

volumes:
  repayments_postgres_data: