apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # 'prometheus' is the Docker service name — Grafana finds it on the network
    url: http://prometheus:9090
    isDefault: true
    editable: true